name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Android build
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make Gradlew Executable
      run: chmod +x android/gradlew
      
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleRelease
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MediBookApp-APK
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30
        
    - name: Upload Build Files
      uses: actions/upload-artifact@v4
      with:
        name: Build-Files
        path: |
          android/app/build/outputs/
          android/build/
        retention-days: 7 